### ISSUE TITLE
Markdown Language Features (built-in) version 1.44.2 report an error in Theia

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7780]
### Bug Description:
When you upgrade the Markdown Language Features (built-in)   version from version 1.39.1 to version 1.44.2, opening a README.md file does not show

An **error** is reported:
**failed: n.window.registerCustomEditorProvider is not a function.**

### Steps to Reproduce:

1. Update package,json with
FROM
"vscode-builtin-markdown-language-features": "https://open-vsx.org/api/vscode/markdown-language-features/1.39.1/file/vscode.markdown-language-features-1.39.1.vsix",
TO
"vscode-builtin-markdown-language-features": "https://open-vsx.org/api/vscode/markdown-language-features/1.44.2/file/vscode.markdown-language-features-1.44.2.vsix",
2. Remove the plugins folder
3.yarn download:plugins
4. Start Theia with a workspace pointing to Theia
5. In the explorer view, locate a README.md file
Select Context menu/Open With/ Preview
--> DO NOT WORK with builtin 1.44.2
--> work with builtin 1.39.1

### Additional Information

- Operating System: UBUNTU 18.04
- Theia Version: LATEST

**Comment by vince-fugnitto** [comment]
@lmcbout the API has been recently marked as final and is not yet supported: https://github.com/eclipse-theia/theia/issues/6636

**Comment by vince-fugnitto** [comment]
I tested with `1.50.0` of the extension and it works well given that `registerCustomEditorProvider` is implemented.
