### ISSUE TITLE
Command Palette is not working after upgrade to 1.25

### ISSUE THREAD

**Issue by BarryDrez** [eclipse-theia/theia#11715]
### Bug Description:
After upgrading my Theia extension to use Theia dependencies V 1.25 (from 1.24), the command palette no longer works.

### Steps to Reproduce:

1.  Upgraded my package.json and changed Theia 1.24.0 dependencies to Theia 1.25.0.
2.  Run my Theia extension
3.  Press F1 or Ctrl+Shift+P
4. A dialog appears with no commands.  Just a single line text area.

The following stack trace appears in the console:

```
logger-protocol.ts:112 root ERROR Failed to execute command: TypeError: inputElements.reduce is not a function
    at QuickInputList.setElements (http://localhost:3400/vendors-node_modules_theia_monaco_lib_browser_monaco-workspace_js.js:48404:39)
    at QuickPick.update (http://localhost:3400/vendors-node_modules_theia_monaco_lib_browser_monaco-workspace_js.js:47161:26)
    at QuickPick.show (http://localhost:3400/vendors-node_modules_theia_monaco_lib_browser_monaco-workspace_js.js:46563:14)
    at QuickPick.show (http://localhost:3400/vendors-node_modules_theia_monaco_lib_browser_monaco-workspace_js.js:47062:15)
    at QuickAccessController.doShowOrPick (http://localhost:3400/vendors-node_modules_theia_monaco_lib_browser_monaco-workspace_js.js:166250:16)
    at QuickAccessController.show (http://localhost:3400/vendors-node_modules_theia_monaco_lib_browser_monaco-workspace_js.js:166156:14)
    at MonacoQuickInputImplementation.open (http://localhost:3400/vendors-node_modules_theia_monaco_lib_browser_monaco-editor-provider_js.js:1326:26)
    at MonacoQuickInputService.open (http://localhost:3400/vendors-node_modules_theia_monaco_lib_browser_monaco-editor-provider_js.js:1425:28)
    at Object.execute (http://localhost:3400/bundle.js:43738:87)
    at CommandRegistry.executeCommand (http://localhost:3400/bundle.js:59082:42)
```

### Additional Information

- Operating System: Windows 10 Enterprise
- Theia Version: 1.25.0

My package.json:
[package.json.txt](https://github.com/eclipse-theia/theia/files/9675936/package.json.txt)

**Comment by BarryDrez** [comment]
Hi @vince-fugnitto, Yes.  I tried with 1.28 and 1.29, and I see the same issue.  Thanks!

**Comment by vince-fugnitto** [comment]
> Hi @vince-fugnitto, Yes. I tried with 1.28 and 1.29, and I see the same issue. Thanks!

Unfortunately it works at each of those tags and master, you'll need to debug a bit further in your application as to why it may not work properly.

**Comment by BarryDrez** [comment]
@vince-fugnitto I don't understand what is causing the error shown in the stack trace.  Is it one of the plugins I am using?  They are the same as the ones being used by Theia Blueprint for the same version.

**Comment by vince-fugnitto** [comment]
@BarryDrez an easy way to confirm would be to start your application without any plugins (so they do not interfere) and confirm that the bug is still present.

**Comment by BarryDrez** [comment]
I removed the plugins, and I still get the error.  Nothing in my extension code has changed.  The only thing I changed were the dependencies as can be seen in my attached package.json.  I looked at the migration guide, and there was nothing I needed to do.

**Comment by vince-fugnitto** [comment]
@BarryDrez unfortunately it is difficult to help without looking at your actual extension:
- I verified that `v1.25.0`, `v1.28.0` and `v1.29.0` works
- verified that your `package.json` works when I remove your custom extension and dependencies I could not find

You'll need to look at your dependencies and custom extension (confirm by removing it if necessary) and debug.
I'm not sure there is more I can do on this end.
